apiVersion: v1
kind: Secret
metadata:
  name: dominos-payment-secret
  namespace: default
type: Opaque
data:
  # These are example base64 encoded values
  # In production, replace with your actual encoded credentials
  # To encode: echo -n "your-value" | base64
  Number: RXhhbXBsZUNyZWRpdENhcmROdW1iZXI=        # Example credit card number
  Expiration: MDEvMjU=                             # Example expiration (01/25)
  SecurityCode: MTIz                               # Example security code (123)
  PostalCode: OTAyMTA=                             # Example postal code (90210)