# Custom values for kube-prometheus-stack Helm chart

# Prometheus configuration
prometheus:
  prometheusSpec:
    # Retention configuration
    retention: 15d
    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    # CPU alert rule
    additionalRuleGroups:
      - name: pizza-alerts
        rules:
          - alert: HighCPUUsage
            expr: (sum by (instance) (irate(node_cpu_seconds_total{mode!="idle"}[5m])) / sum by (instance) (irate(node_cpu_seconds_total[5m]))) * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High CPU usage detected
              description: "CPU usage is above 80% for 5 minutes on {{ $labels.instance }}"

# AlertManager configuration
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'pizza-webhook'
      routes:
      - match:
          alertname: HighCPUUsage
        receiver: 'pizza-webhook'
    receivers:
    - name: 'pizza-webhook'
      webhook_configs:
      - url: 'https://your-azure-function-url.azurewebsites.net/api/orderpizza'
        send_resolved: true

# Grafana configuration
grafana:
  adminPassword: "pizza123"
  persistence:
    enabled: true
    size: 5Gi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      cpu-dashboard:
        json: |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            },
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "id": 1,
            "links": [],
            "panels": [
              {
                "alert": {
                  "alertRuleTags": {},
                  "conditions": [
                    {
                      "evaluator": {
                        "params": [
                          80
                        ],
                        "type": "gt"
                      },
                      "operator": {
                        "type": "and"
                      },
                      "query": {
                        "params": [
                          "A",
                          "5m",
                          "now"
                        ]
                      },
                      "reducer": {
                        "params": [],
                        "type": "avg"
                      },
                      "type": "query"
                    }
                  ],
                  "executionErrorState": "alerting",
                  "for": "5m",
                  "frequency": "1m",
                  "handler": 1,
                  "name": "CPU Usage alert",
                  "noDataState": "no_data",
                  "notifications": []
                },
                "aliasColors": {},
                "bars": false,
                "dashLength": 10,
                "dashes": false,
                "datasource": "Prometheus",
                "fieldConfig": {
                  "defaults": {
                    "custom": {}
                  },
                  "overrides": []
                },
                "fill": 1,
                "fillGradient": 0,
                "gridPos": {
                  "h": 9,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "hiddenSeries": false,
                "id": 2,
                "legend": {
                  "avg": false,
                  "current": false,
                  "max": false,
                  "min": false,
                  "show": true,
                  "total": false,
                  "values": false
                },
                "lines": true,
                "linewidth": 1,
                "nullPointMode": "null",
                "options": {
                  "alertThreshold": true
                },
                "percentage": false,
                "pluginVersion": "7.3.7",
                "pointradius": 2,
                "points": false,
                "renderer": "flot",
                "seriesOverrides": [],
                "spaceLength": 10,
                "stack": false,
                "steppedLine": false,
                "targets": [
                  {
                    "expr": "(sum by (instance) (irate(node_cpu_seconds_total{mode!\"idle\"}[5m])) / sum by (instance) (irate(node_cpu_seconds_total[5m]))) * 100",
                    "interval": "",
                    "legendFormat": "CPU Usage - {{instance}}",
                    "refId": "A"
                  }
                ],
                "thresholds": [
                  {
                    "colorMode": "critical",
                    "fill": true,
                    "line": true,
                    "op": "gt",
                    "value": 80
                  }
                ],
                "timeFrom": null,
                "timeRegions": [],
                "timeShift": null,
                "title": "CPU Usage",
                "tooltip": {
                  "shared": true,
                  "sort": 0,
                  "value_type": "individual"
                },
                "type": "graph",
                "xaxis": {
                  "buckets": null,
                  "mode": "time",
                  "name": null,
                  "show": true,
                  "values": []
                },
                "yaxes": [
                  {
                    "format": "percent",
                    "label": null,
                    "logBase": 1,
                    "max": "100",
                    "min": "0",
                    "show": true
                  },
                  {
                    "format": "short",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": true
                  }
                ],
                "yaxis": {
                  "align": false,
                  "alignLevel": null
                }
              }
            ],
            "schemaVersion": 26,
            "style": "dark",
            "tags": [],
            "templating": {
              "list": []
            },
            "time": {
              "from": "now-6h",
              "to": "now"
            },
            "timepicker": {},
            "timezone": "",
            "title": "CPU Usage Dashboard",
            "uid": "cpu-usage",
            "version": 1
          }