apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-function
  namespace: {{ .Values.global.namespace }}
  labels:
    app: azure-function
    {{- include "k8s-pizza-observability.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.azureFunction.replicas | default 1 }}
  selector:
    matchLabels:
      app: azure-function
  template:
    metadata:
      labels:
        app: azure-function
    spec:
      containers:
      - name: function
        image: "{{ .Values.azureFunction.image.repository }}:{{ .Values.azureFunction.image.tag }}"
        imagePullPolicy: {{ .Values.azureFunction.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.azureFunction.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}