# Jekyll site configuration

# Theme settings
theme: jekyll-theme-cayman

# Site settings
title: Kubernetes Pizza Observability
description: Order pizza automatically when your Kubernetes cluster is under high load!
tagline: Modern Kubernetes Monitoring with a Delicious Twist

# Social links
github_username: yourusername
twitter_username: yourusername

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
highlight: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Custom settings
show_downloads: true
logo: /assets/images/k8s-pizza-logo.svg
favicon: /favicon.svg

# External resources
external_resources:
  - href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    type: "stylesheet"
  - href: "https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&family=Montserrat:wght@400;500;600;700;800&family=Fira+Code&display=swap"
    type: "stylesheet"